### ISSUE TITLE
how can i use?

### ISSUE THREAD

**Issue by davut5** [leznupar999/SSYoutubeParser#1]
how can i use it.  how to install? And please put swift 1.2

**Comment by grasebit** [comment]
Please look README.md.
Please use tag "swift1.2".

**Comment by davut5** [comment]
now it is ok. thank you very much. can i ask you a question. 
i want to record youtube video to my device. can i make it? (MP4)
download it or write from buffer while youtube video is playing?

**Comment by grasebit** [comment]
I do not know.
